# Generated by Django 2.2.6 on 2019-11-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_category_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
