# Generated by Django 2.2.6 on 2019-11-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_storeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_warehouse_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_warehouse_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0244123456', max_length=50),
        ),
    ]
