# Generated by Django 2.2.6 on 2019-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20191125_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
