# Generated by Django 2.2.6 on 2019-11-26 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20191126_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('shelf', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Shelf Item',
                'verbose_name_plural': 'Shelf Items',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='shelved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='StoreItem',
        ),
        migrations.AddField(
            model_name='shelfitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AddField(
            model_name='shelfitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
