# Generated by Django 2.2.6 on 2019-11-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
